(+) Adds documentation about git workflow at liber
libercapital/guides pull request #2
Opened 2021-07-07 13:15 UTC by andrewhenriquef

2021-07-07 19:38 UTC, guilpejon requested changes
Não sei se é melhor corrigir os pontos que levantei ou criar eles do zero pq essas infos parecem meio desatualizadas

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +    - [snakehole](https://github.com/libercapital/snakehole)/[wormhole](https://github.com/libercapital/wormhole)
```suggestion
    - [snakehole](https://github.com/libercapital/snakehole)
```

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +    - [liber-sign]()
```suggestion
    - [liber-sign](https://github.com/libercapital/liber-sign)
```

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +**[Liber on github](https://github.com/libercapital)**
Acho que podemos colocar `Main projects` aqui (linha de baixo), porque se o cara estiver lendo isso ele já está na organização da Liber

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +    - [guides](https://github.com/libercapital/guides)
Acho que podemos tirar essa linha pelo mesmo motivo do comentário anterior: o cara já vai estar aqui 😄

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +- master → produção
Pode passar tudo pra inglês pra manter o padrão do liber-guides até então?

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +  - Circle-CI → tests;
Precisa atualizar essa parte

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +2 approval are required to be able to merge your PR into release:
Aqui só precisa do approval de uma pessoa, desde que ela seja code owner

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +When this is turned on, makes the PR being automatically merged into release branch when passed all the check's
```suggestion
When this is turned on, makes the PR being automatically merged into release branch when passed all the checks
```

2021-07-07 19:38 UTC, guilpejon commented on git/README.md
> +  - This is useful to not run the check's, to notice other developers that you are doing changes to code, and to declare that your code is not able to be merged
```suggestion
  - This is useful to not run the checks, to notice other developers that you are doing changes to code, and to declare that your code is not able to be merged
```

2021-07-07 21:09 UTC, andrewhenriquef commented on git/README.md
> +**[Liber on github](https://github.com/libercapital)**
Aqui a ideia é renomear o link que nem no exemplo abaixo ? 

```suggestion
**[Main projects](https://github.com/libercapital)**
```

2021-07-07 21:13 UTC, andrewhenriquef commented on git/README.md
> +  - Circle-CI → tests;
Github actions ? Devo adicionar algo mais nessa parte ?

2021-07-12 21:06 UTC, guilpejon commented on git/README.md
> +  - Circle-CI → tests;
Ia falar pra vc adicionar aqui todas as github actions do monolito mas, pensando bem, acho ruim a gente fazer isso. Esses guias são pra Liber inteira, não pra projetos específicos. Só podemos colocar aqui o que realmente está sendo usado em todos os repositórios. Dá uma revisada no arquivo novamente em busca desses pontos e pode remover. Até algumas questões de branch não fazem sentido ficar aqui pois acho que os repos de python não usam o mesmo esquema dos repos de ruby.

2021-07-13 12:35 UTC, andrewhenriquef commented on git/README.md
> +  - Circle-CI → tests;
Talvez dê para adicionar o fluxo de quando não existir um Jira relacionado a tarefa, caso existir algum padrão. Para esses repositórios em `python`, `java` , `c`, `elixir` e etc, não existe um padrão de commit para eles ? 

Caso não existir podemos remover mesmo :cry:

2021-07-13 14:49 UTC, guilpejon commented on git/README.md
> +  - Circle-CI → tests;
Talvez até exista um padrão implícito mas aí temos que pensar em como organizar isso no guides melhor. Até termos um padrão explícito pra tudo acho melhor tirar e adicionar depois.

2021-07-13 18:44 UTC, merged