(+) Adds portuguese-english dictionary
libercapital/guides pull request #3
Opened 2021-07-07 13:27 UTC by andrewhenriquef

2021-07-07 19:43 UTC, guilpejon requested changes
Ia falar pra trocar o nome do arquivo pra "portuguese-english" pra manter em inglês mas acho que é legal chamar de `README.md` mesmo pra manter o padrão

2021-07-07 19:43 UTC, guilpejon commented on dictionary/portugues-english.md
> +Duplicata → bill, Duplicata
Não entendi o porquê de duplicar a palavra em português na direita depois da vírgula nessas linhas 🤔

2021-07-07 20:04 UTC, andrewhenriquef commented on dictionary/portugues-english.md
> +Duplicata → bill, Duplicata
Por conta de que ainda existem algumas variaveis em português no monolito, minha intenção é de deixar claro que não usamos mais desta maneira.

![image](https://user-images.githubusercontent.com/4303152/124821491-287dc280-df45-11eb-8ab4-9e3a74901454.png)

2021-07-07 20:05 UTC, andrewhenriquef commented on dictionary/portugues-english.md
> +Duplicata → bill, Duplicata
Outro ponto que quero confrmar com você antes de realizar a alteração, o arquivo está atualmente com o nome de `portuguese-english`, mudo para `README` então ?

2021-07-12 21:04 UTC, guilpejon commented on dictionary/portugues-english.md
> +Duplicata → bill, Duplicata
Então, mas não era só deixar, por exemplo, `Duplicata → bill`? Acho que não precisaria repetir `duplicata` no final.

Sobre o nome do arquivo, muda pra `README` pra gente manter o padrão

2021-07-13 14:35 UTC, guilpejon approved these changes

2021-07-13 14:35 UTC, merged