Joins vs Includes
libercapital/guides pull request #7
Opened 2021-07-26 19:15 UTC by joseantonnio

It is quite common to forget the difference or not even notice the incorrect use of includes and joins. This documentation is intended to assist in Liber's pull requests or guide new developers.

2021-08-20 18:43 UTC, guilpejon requested changes

2021-08-20 18:43 UTC, guilpejon commented on rails/sample.rb
> +users = User.includes(:company).where(companies: { status: :onboarded })
Acho que aqui devia ser `joins`, né?

2021-08-24 16:31 UTC, joseantonnio commented on rails/sample.rb
> +users = User.includes(:company).where(companies: { status: :onboarded })
Yep

2021-08-24 18:27 UTC, guilpejon approved these changes
Valeu pelo PR, Zé!

2021-08-24 18:27 UTC, merged